# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hello_world <- function() {
    invisible(.Call(`_RCRnormCpp_hello_world`))
}

#' @title
#' Linear Regression
#' @description
#' Performs basic linear regression
#' @param X explanatory variables (should be a matrix)
#' @param y the response variable 
#' @return
#' A list containing coefficients and residuals
#' @export
linearRegression <- function(X, y) {
    .Call(`_RCRnormCpp_linearRegression`, X, y)
}

#' @title
#' Inv-gamma
#' @description
#' Generate inverse gamma 
#' @export
rinvGamma <- function(n, shape, rate) {
    .Call(`_RCRnormCpp_rinvGamma`, n, shape, rate)
}

lbLambdaUb <- function(lambda, lb, ub) {
    .Call(`_RCRnormCpp_lbLambdaUb`, lambda, lb, ub)
}

lambdaLbUb <- function(lambda, lb, ub) {
    .Call(`_RCRnormCpp_lambdaLbUb`, lambda, lb, ub)
}

lbUbLambda <- function(lambda, lb, ub) {
    .Call(`_RCRnormCpp_lbUbLambda`, lambda, lb, ub)
}

rtruncatedStandardNormPositive <- function(n, lb, ub) {
    .Call(`_RCRnormCpp_rtruncatedStandardNormPositive`, n, lb, ub)
}

rtruncatedStandardNormPositiveExtreme <- function(n, lb, ub) {
    .Call(`_RCRnormCpp_rtruncatedStandardNormPositiveExtreme`, n, lb, ub)
}

rtruncatedStandardNormNegative <- function(n, lb, ub) {
    .Call(`_RCRnormCpp_rtruncatedStandardNormNegative`, n, lb, ub)
}

rtruncatedStandardNormNegativeExtreme <- function(n, lb, ub) {
    .Call(`_RCRnormCpp_rtruncatedStandardNormNegativeExtreme`, n, lb, ub)
}

rtruncatedStandardNorm <- function(n, lb, ub) {
    .Call(`_RCRnormCpp_rtruncatedStandardNorm`, n, lb, ub)
}

rtruncatedNorm <- function(n, lb, ub, mu, sd) {
    .Call(`_RCRnormCpp_rtruncatedNorm`, n, lb, ub, mu, sd)
}

#' @title
#' Gibbs sampler
#' @description
#' One MCMC chain
#' @export
NULL

generateSampleMatrix <- function(p, n_iter) {
    .Call(`_RCRnormCpp_generateSampleMatrix`, p, n_iter)
}

sampler <- function(dat, priors, initial_values, pos_conc, n_iter) {
    .Call(`_RCRnormCpp_sampler`, dat, priors, initial_values, pos_conc, n_iter)
}

findA1 <- function(neg_dat, bi, cc, d_neg, n_patient) {
    .Call(`_RCRnormCpp_findA1`, neg_dat, bi, cc, d_neg, n_patient)
}

findA2 <- function(pos_dat, bi, pos_conc, d_pos, n_patient) {
    .Call(`_RCRnormCpp_findA2`, pos_dat, bi, pos_conc, d_pos, n_patient)
}

findA3 <- function(hk_dat, bi, phi, kappa_hk, d_hk, n_patient, n_hk) {
    .Call(`_RCRnormCpp_findA3`, hk_dat, bi, phi, kappa_hk, d_hk, n_patient, n_hk)
}

findA4 <- function(reg_dat, bi, phi, kappa_reg, d_reg, n_patient, n_reg) {
    .Call(`_RCRnormCpp_findA4`, reg_dat, bi, phi, kappa_reg, d_reg, n_patient, n_reg)
}

updateAi <- function(dat, bi, cc, d_neg, pos_conc, d_pos, phi, kappa_hk, d_hk, kappa_reg, d_reg, mu_a, sigma2e_neg, sigma2e, sigma2a) {
    .Call(`_RCRnormCpp_updateAi`, dat, bi, cc, d_neg, pos_conc, d_pos, phi, kappa_hk, d_hk, kappa_reg, d_reg, mu_a, sigma2e_neg, sigma2e, sigma2a)
}

findB1 <- function(neg_dat, ai, cc, d_neg, n_patient) {
    .Call(`_RCRnormCpp_findB1`, neg_dat, ai, cc, d_neg, n_patient)
}

findB2 <- function(pos_dat, ai, pos_conc, d_pos, n_patient) {
    .Call(`_RCRnormCpp_findB2`, pos_dat, ai, pos_conc, d_pos, n_patient)
}

findB3 <- function(hk_dat, ai, phi, kappa_hk, d_hk, n_patient, n_hk) {
    .Call(`_RCRnormCpp_findB3`, hk_dat, ai, phi, kappa_hk, d_hk, n_patient, n_hk)
}

findB4 <- function(reg_dat, ai, phi, kappa_reg, d_reg, n_patient, n_reg) {
    .Call(`_RCRnormCpp_findB4`, reg_dat, ai, phi, kappa_reg, d_reg, n_patient, n_reg)
}

updateBi <- function(dat, ai, cc, d_neg, pos_conc, d_pos, phi, kappa_hk, d_hk, kappa_reg, d_reg, mu_b, sigma2e_neg, sigma2e, sigma2b) {
    .Call(`_RCRnormCpp_updateBi`, dat, ai, cc, d_neg, pos_conc, d_pos, phi, kappa_hk, d_hk, kappa_reg, d_reg, mu_b, sigma2e_neg, sigma2e, sigma2b)
}

updateCc <- function(dat, ai, bi, d_neg, sigma2e_neg, priors) {
    .Call(`_RCRnormCpp_updateCc`, dat, ai, bi, d_neg, sigma2e_neg, priors)
}

updateDhk <- function(dat, ai, bi, phi, kappa_hk, sigma2e, sigma2d) {
    .Call(`_RCRnormCpp_updateDhk`, dat, ai, bi, phi, kappa_hk, sigma2e, sigma2d)
}

updateDneg <- function(dat, ai, bi, cc, sigma2e_neg, sigma2d_neg) {
    .Call(`_RCRnormCpp_updateDneg`, dat, ai, bi, cc, sigma2e_neg, sigma2d_neg)
}

updateDpos <- function(dat, ai, bi, pos_conc, sigma2e, sigma2d) {
    .Call(`_RCRnormCpp_updateDpos`, dat, ai, bi, pos_conc, sigma2e, sigma2d)
}

updateDreg <- function(dat, ai, bi, phi, kappa_reg, sigma2e, sigma2d) {
    .Call(`_RCRnormCpp_updateDreg`, dat, ai, bi, phi, kappa_reg, sigma2e, sigma2d)
}

updateKappaHk <- function(dat, ai, bi, phi, d_hk, lambda_hk, sigma2e, sigma2kappa_hk) {
    .Call(`_RCRnormCpp_updateKappaHk`, dat, ai, bi, phi, d_hk, lambda_hk, sigma2e, sigma2kappa_hk)
}

updateKappaReg <- function(dat, ai, bi, phi, d_reg, lambda_reg, sigma2e, sigma2kappa_reg) {
    .Call(`_RCRnormCpp_updateKappaReg`, dat, ai, bi, phi, d_reg, lambda_reg, sigma2e, sigma2kappa_reg)
}

updateLambdaHk <- function(dat, kappa_hk, sigma2kappa_hk, priors) {
    .Call(`_RCRnormCpp_updateLambdaHk`, dat, kappa_hk, sigma2kappa_hk, priors)
}

updateLambdaReg <- function(dat, kappa_reg, sigma2kappa_reg, priors) {
    .Call(`_RCRnormCpp_updateLambdaReg`, dat, kappa_reg, sigma2kappa_reg, priors)
}

updateMuA <- function(dat, ai, sigma2a, priors) {
    .Call(`_RCRnormCpp_updateMuA`, dat, ai, sigma2a, priors)
}

updateMuB <- function(dat, bi, sigma2b, priors) {
    .Call(`_RCRnormCpp_updateMuB`, dat, bi, sigma2b, priors)
}

updatePhi <- function(dat, ai, bi, kappa_hk, d_hk, kappa_reg, d_reg, sigma2e, priors) {
    .Call(`_RCRnormCpp_updatePhi`, dat, ai, bi, kappa_hk, d_hk, kappa_reg, d_reg, sigma2e, priors)
}

updateSigma2D <- function(dat, d_pos, d_hk, d_reg, priors) {
    .Call(`_RCRnormCpp_updateSigma2D`, dat, d_pos, d_hk, d_reg, priors)
}

updateSigma2Dneg <- function(dat, d_neg, priors) {
    .Call(`_RCRnormCpp_updateSigma2Dneg`, dat, d_neg, priors)
}

updateSigma2E <- function(dat, ai, bi, pos_conc, phi, kappa_hk, kappa_reg, d_pos, d_hk, d_reg, priors) {
    .Call(`_RCRnormCpp_updateSigma2E`, dat, ai, bi, pos_conc, phi, kappa_hk, kappa_reg, d_pos, d_hk, d_reg, priors)
}

updateSigma2Eneg <- function(dat, ai, bi, cc, d_neg, priors) {
    .Call(`_RCRnormCpp_updateSigma2Eneg`, dat, ai, bi, cc, d_neg, priors)
}

updateSigma2KappaHk <- function(dat, kappa_hk, lambda_hk, priors) {
    .Call(`_RCRnormCpp_updateSigma2KappaHk`, dat, kappa_hk, lambda_hk, priors)
}

updateSigma2KappaReg <- function(dat, kappa_reg, lambda_reg, priors) {
    .Call(`_RCRnormCpp_updateSigma2KappaReg`, dat, kappa_reg, lambda_reg, priors)
}

updateSigma2a <- function(dat, ai, mu_a, priors) {
    .Call(`_RCRnormCpp_updateSigma2a`, dat, ai, mu_a, priors)
}

updateSigma2b <- function(dat, bi, mu_b, priors) {
    .Call(`_RCRnormCpp_updateSigma2b`, dat, bi, mu_b, priors)
}

